name: 01 - Release to GitHub Packages

on:
  push:
    branches:
      - main

run-name: Release to GitHub Packages - ${{ github.actor }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Required for signing the tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get previous tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20      # Latest supported version for Runners - April 2025
          registry-url: https://npm.pkg.github.com/
          scope: "@renan-alm"   # Replace with your GitHub username

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check if version has changed
        id: check_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo '')
          echo "Previous tag: $PREVIOUS_TAG"
          if [[ "$PREVIOUS_TAG" == "v$CURRENT_VERSION" ]]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "Version has not changed, skipping publish"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Version has changed, proceeding with publish"
          fi
        env:
          GITHUB_OUTPUT: ${{ github.action_path }}/output.env

      # npm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
      # echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      - name: Publish to GitHub Packages
        if: steps.check_version.outputs.changed == 'true'
        run: |
          npm config set _auth $NODE_AUTH_TOKEN 
          npm config set registry $NPM_REGISTRY_URL 
          npm config set always-auth=true 
          npm config set email=renan-alm@github.com
          npm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git tag
        if: steps.check_version.outputs.changed == 'true'
        run: |
          git tag -a "v${{ steps.check_version.outputs.CURRENT_VERSION }}" -m "Release v${{ steps.check_version.outputs.CURRENT_VERSION }}"
          git push origin "v${{ steps.check_version.outputs.CURRENT_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
