name: 01 - Release to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

run-name: Release to GitHub Packages - ${{ github.actor }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write # Required for signing the tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get previous tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20      # Latest supported version for Runners - April 2025
          registry-url: https://npm.pkg.github.com/
          scope: "@renan-alm"   # Replace with your GitHub username

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check if version has changed
        id: check_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo CURRENT_VERSION=$CURRENT_VERSION >> "$GITHUB_OUTPUT"
          echo "Current version: $CURRENT_VERSION"
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo '')
          echo "Previous tag: $PREVIOUS_TAG"
          if [[ "$PREVIOUS_TAG" == "v$CURRENT_VERSION" ]]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "Version has not changed, skipping publish"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Version has changed, proceeding with publish"
          fi
        env:
          GITHUB_OUTPUT: ${{ github.action_path }}/output.env

      # npm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
      # echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      - name: Publish to GitHub Packages
        if: steps.check_version.outputs.changed == 'true'
        run: |
          npm config set registry $NPM_REGISTRY_URL
          npm config set email=renan-alm@github.com
          npm config set //npm.pkg.github.com/:_auth $NODE_AUTH_TOKEN
          npm login --registry=https://npm.pkg.github.com/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_REGISTRY_URL: https://npm.pkg.github.com/

      - name: Print log if Publish failed
        if: steps.check_version.outputs.changed == 'true' && failure()
        run: |
          ls -la
          echo "Publish failed, check the logs for more details"
          last_file=$(ls -la | grep '^-' | awk '{print $NF}' | tail -n 1)
          echo Printing $last_file ...
          cat "$last_file"

      - name: Create Git tag (if applicable)
        run: |
          TAG_NAME="v${{ steps.check_version.outputs.CURRENT_VERSION }}"
          # Check if the tag already exists
          if git show-ref --tags "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping tag creation."
          else
            git config --global user.email "renan-alm@github.com"
            git config --global user.name "Renan Alm"
            git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
            git push origin "$TAG_NAME"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
