name: 02 - Test Action

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

run-name: Test Action - ${{ github.event_name }}

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Test the Action
        uses: ./ # Uses an action in the root directory
        id: action-test
        with:
          user-name: 'Renan Almeida'

      - name: Ensure the output greeting is correct
        if: steps.action-test.outputs.greeting == 'Hello Renan Almeida!'
        run: |
          echo "Greeting matches expected value: ${{ steps.action-test.outputs.greeting }}"

      - name: Output if greeting does not match
        if: steps.action-test.outputs.greeting != 'Hello Renan Almeida!'
        run: |
          echo "Greeting does not match expected value."
          echo "Expected: Hello Renan Almeida!"
          echo "Actual: ${{ steps.action-test.outputs.greeting }}"
          exit 1

      - name: Get the output time created during Action run
        run: echo "The time was ${{ steps.action-test.outputs.time }}"
